name: refresh_dashboard

on:
  push:
    branches: [ main ]
  schedule:  
    - cron: '15 */6 * * *'

jobs: 
  build:
    runs-on: macOS-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - name: Install packages
      run: Rscript -e 'install.packages(c("rmarkdown", "flexdashboard", "readr", "dplyr", "plotly", "zoo"))'
    - name: Render Site
      run: Rscript -e 'rmarkdown::render_site()'
    - name: Commit files
      run: |
        git config --local user.name mozammel47
        git config --local user.email "mozammel_hoque@live.com"
        git add *
        git commit -am "GH ACTION Headlines $(date)"
        git push origin main
