name: refresh_dashboard

on:
  push:
    branches: [ main ]

jobs: 
  render:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Install packages
      run: Rscript -e 'install.packages(c("rmarkdown", "flexdashboard", "dplyr", "plotly", "zoo"))'
    - name: Render Site
      run: Rscript -e 'rmarkdown::render_site()'
    - name: Commit files
      run: |
        git config --local user.name mozammel47
        git config --local user.email "mozammel_hoque@live.com"
        git add data/*
        git commit -am "GH ACTION Headlines $(date)"
        git push origin main
